export type Language = 'nb' | 'en' | 'ko';
const copy = {
  subtitle:['Lær det koreanske alfabetet','Learn the Korean alphabet','한글을 배워 보세요'],
  quiz:['Quiz','Quiz','퀴즈'], exam:['Eksamen','Exam','시험'], cards:['Flashcards','Flashcards','학습 카드'],
  overview:['Lær og utforsk','Learn & explore','배우고 탐색하기'], stats:['Din fremgang','Your progress','나의 학습 기록'],
  language:['Språk','Language','언어'], sound:['Lyd på','Sound on','소리 켜짐'], mute:['Lyd av','Sound off','소리 꺼짐'],
  groups:['Hva vil du øve på?','What would you like to practise?','무엇을 연습할까요?'],
  consonants:['Konsonanter','Basic consonants','기본 자음'], vowels:['Vokaler','Basic vowels','기본 모음'],
  tense:['Doble konsonanter','Tense consonants','쌍자음'], extra:['Flere vokaler','More vowels','추가 모음'],
  syllables:['Stavelser','Syllables','음절'], finals:['Stavelser med 받침','Syllables with batchim','받침이 있는 음절'],
  all:['Alle','All','전체'], basic:['Grunntegn','Basics','기본 글자'], clear:['Tøm','Clear','해제'],
  chosen:['valgte tegn','selected characters','선택한 글자'], mode:['Hvordan vil du svare?','How will you answer?','어떻게 답할까요?'],
  typing:['Skriv svaret','Type the answer','직접 입력'], choice:['Flervalg','Multiple choice','객관식'],
  direction:['Spørsmålsretning','Question direction','문제 방향'], read:['Hangeul → latinske bokstaver','Hangeul → romanization','한글 → 로마자'],
  write:['Latinske bokstaver → hangeul','Romanization → Hangeul','로마자 → 한글'],
  count:['Antall spørsmål','Number of questions','문제 수'], start:['Start quiz','Start quiz','퀴즈 시작'],
  listen:['Hør uttalen','Hear pronunciation','발음 듣기'],
  audioMissing:['Lydklippet kunne ikke lastes eller spilles av.','The audio clip could not be loaded or played.','음성 파일을 불러오거나 재생할 수 없습니다.'],
  audioUnavailable:['Lydklipp mangler for denne stavelsen','No audio clip for this syllable','이 음절의 음성 파일이 없습니다'],
  audioRetry:['Prøv igjen','Try again','다시 시도'],
  recording:['Opptak','Recording','녹음'],
  audioSample:['Eksempeluttale','Example pronunciation','발음 예시'],
  listenName:['Hør bokstavnavnet','Hear the letter name','글자 이름 듣기'],
  listenVowel:['Hør vokallyden','Hear the vowel sound','모음 소리 듣기'],
  listenSyllable:['Hør stavelsen','Hear the syllable','음절 듣기'],
  listenExample:['Hør eksemplet','Hear the example','예시 듣기'],
  syllableExample:['Eksempel i stavelse','Example in a syllable','음절 속 발음 예시'],
  audioGuide:['Bokstavnavn og bokstavlyd er ulike ting. Konsonanteksemplene er hele stavelser: i 가 (ga) kommer a fra ㅏ, ikke fra ㄱ.','Letter names and letter sounds are different. Consonant examples are whole syllables: in 가 (ga), the a comes from ㅏ, not ㄱ.','글자 이름과 글자 소리는 다릅니다. 자음 예시는 완전한 음절입니다. 가(ga)의 a는 ㄱ이 아니라 ㅏ의 소리입니다.'],
  ieungAudioNote:['ㅇ er stum i starten: i 아 (a) kommer lyden fra ㅏ. Til slutt er ㅇ ng: lytt til slutten av 앙 (ang). Bokstavnavnet er 이응 (ieung).','ㅇ is silent initially: in 아 (a), the sound comes from ㅏ. Finally, ㅇ is ng: listen to the end of 앙 (ang). Its letter name is 이응 (ieung).','ㅇ은 초성에서 소리가 없습니다. 아(a)의 소리는 ㅏ에서 납니다. 종성 ㅇ은 ng입니다. 앙(ang)의 끝소리를 들어 보세요. 글자 이름은 이응입니다.'],
  answer:['Ditt svar','Your answer','정답 입력'], check:['Sjekk svaret','Check answer','정답 확인'], next:['Neste','Next','다음'],
  previous:['Forrige','Previous','이전'], cancel:['Avslutt økten','End session','학습 종료'], cancelConfirm:['Avslutte økten? Besvarte spørsmål blir lagret.','End this session? Answered questions will be saved.','학습을 종료할까요? 답한 문제는 저장됩니다.'],
  correct:['Riktig!','Correct!','정답!'], wrong:['Ikke helt.','Not quite.','다시 확인해 보세요.'], solution:['Riktig svar','Correct answer','정답'],
  timeout:['Tiden er ute','Time is up','시간 초과'], question:['Spørsmål','Question','문제'], score:['Riktige','Correct','정답 수'],
  romanChoicePrompt:['Velg riktig svar med latinske bokstaver','Choose the correct romanization','올바른 로마자를 선택하세요'],
  glyphChoicePrompt:['Velg riktig hangeul-tegn','Choose the correct Hangeul character','올바른 한글을 선택하세요'],
  romanPrompt:['Skriv med latinske bokstaver','Type the romanization','로마자를 입력하세요'], glyphPrompt:['Skriv hangeul-tegnet','Type the Hangeul character','한글을 입력하세요'],
  koreanKeyboard:['Bruk det koreanske tastaturet på telefonen eller PC-en.','Use the Korean keyboard on your phone or computer.','휴대폰이나 컴퓨터의 한국어 키보드를 사용하세요.'],
  results:['Quizresultat','Quiz results','퀴즈 결과'],
  retry:['Øv på feilene','Practise mistakes','틀린 문제 연습'], again:['Ta en ny quiz','Start another quiz','새 퀴즈 시작'],
  finished:['Økten er ferdig','Session complete','학습 완료'], accuracy:['Nøyaktighet','Accuracy','정확도'],
  examTitle:['Den store hangeul-testen','The Hangeul challenge','한글 실력 시험'],
  locked:['Eksamen åpner snart','The exam opens soon','시험이 곧 열립니다'],
  unlockDate:['Mandag 12. oktober 2026 · kl. 08:00 norsk tid','Monday 12 October 2026 · 08:00 Norway time','2026년 10월 12일 월요일 · 노르웨이 시간 08:00 (한국 시간 15:00)'],
  days:['dager','days','일'], hours:['timer','hours','시간'], minutes:['minutter','minutes','분'], seconds:['sekunder','seconds','초'],
  syllabus:['Velg pensum','Choose a syllabus','시험 범위 선택'], letters:['Alle 40 bokstaver','All 40 letters','전체 40개 글자'],
  full:['Bokstaver og stavelser','Letters & syllables','글자와 음절'], examStart:['Start eksamen','Start exam','시험 시작'],
  examRule:['100 % riktig · 5 s per tegn · én feil avslutter','100% correct · 5 s per character · one mistake ends the exam','정확도 100% · 글자당 5초 · 오답 시 종료'],
  passed:['Eksamen bestått','Exam passed','시험 합격'], failed:['Eksamen ikke bestått','Exam failed','시험 불합격'],
  attempted:['Besvart','Answered','답한 문제'],
  filter:['Tegngruppe','Character group','글자 종류'], shuffle:['Stokk kort','Shuffle cards','카드 섞기'],
  flip:['Trykk for å snu · mellomrom','Tap to flip · space','눌러서 뒤집기 · 스페이스'],
  needsPractice:['Må øves på','Needs practice','복습 필요'], mastered:['Mestret','Mastered','학습 완료'],
  reviewOnly:['Kun tegn som må øves på','Only characters needing practice','복습할 글자만'],
  emptyReview:['Ingen tegn å repetere her ennå. Velg en annen gruppe eller slå av filteret.','No characters to review here yet. Choose another group or turn off the filter.','복습할 글자가 없습니다. 다른 종류를 선택하거나 필터를 해제하세요.'],
  search:['Søk etter tegn eller romanisering','Search characters or romanization','글자 또는 로마자 검색'],
  builder:['Stavelsesbygger','Syllable builder','음절 만들기'], onset:['Startkonsonant','Initial consonant','초성'],
  medial:['Vokal','Vowel','중성'], final:['Sluttkonsonant','Final consonant','종성'], none:['Ingen','None','없음'],
  syllableNote:['Romaniseringen gjelder en enkelt stavelse. Uttalen kan endres når stavelser settes sammen til ord.','Romanization is for an isolated syllable. Pronunciation can change when syllables form words.','로마자는 단독 음절을 기준으로 합니다. 단어에서는 발음이 달라질 수 있습니다.'],
  consonantNote:['ㄱ, ㄷ og ㅂ har ulike lyder etter plassering. ㄹ kan være r eller l. ㅇ er stum først i en stavelse og ng til slutt.','ㄱ, ㄷ and ㅂ change sound with position. ㄹ can be r or l. ㅇ is silent initially and ng in final position.','ㄱ, ㄷ, ㅂ은 위치에 따라 소리가 달라집니다. ㄹ은 r 또는 l로 적습니다. ㅇ은 초성에서 소리가 없고 종성에서 ng로 적습니다.'],
  vowelNote:['eo og eu er én vokallyd hver. De uttales ikke som to separate bokstaver. ㅐ og ㅔ høres ofte like ut i moderne koreansk.','eo and eu each represent one vowel, not two separate sounds. ㅐ and ㅔ often sound alike in modern Korean.','eo와 eu는 각각 하나의 모음 소리입니다. 현대 한국어에서는 ㅐ와 ㅔ가 비슷하게 들리는 경우가 많습니다.'],
  extraNote:['Denne gruppen samler 11 vokalbokstaver utover de 10 grunnvokalene. Ikke alle er fonetisk diftonger.','This group contains 11 vowel letters beyond the 10 basic vowel letters. They are not all phonetic diphthongs.','이 그룹은 기본 모음 10개 외의 모음 11개입니다. 음성학적으로 모두 이중 모음인 것은 아닙니다.'],
  finalNote:['받침 er konsonanten nederst i stavelsen. I slutten av en isolert stavelse reduseres sluttlydene til k, n, t, l, m, p eller ng.','Batchim is the consonant at the bottom of a syllable. At the end of an isolated syllable, final sounds reduce to k, n, t, l, m, p or ng.','받침은 음절 아래에 놓입니다. 단독 음절의 끝소리는 ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅇ 중 하나로 발음됩니다.'],
  statsIntro:['Tre riktige svar på rad gir mestring. Feil svar sender tegnet tilbake til øving.','Three correct answers in a row mark a character as mastered. A mistake sends it back to practice.','같은 글자를 세 번 연속 맞히면 학습 완료로 표시됩니다. 틀리면 다시 복습 목록으로 돌아갑니다.'],
  answered:['Besvarte spørsmål','Questions answered','답한 문제 수'], best:['Beste serie','Best streak','최고 연속 정답'],
  mastery:['Mestrede bokstaver','Letters mastered','학습 완료 글자'], hard:['Her kan du bli bedre','Worth another look','다시 연습할 글자'],
  noStats:['Ingen svar ennå. Ta en quiz, så finner vi ut hva du bør øve på.','No answers yet. Take a quiz to find out what to practise.','아직 기록이 없습니다. 퀴즈로 연습할 글자를 찾아보세요.'],
  noMistakes:['Ingen feil registrert. Fortsett å øve!','No mistakes recorded. Keep practising!','틀린 문제가 없습니다. 계속 연습해 보세요!'],
  reset:['Nullstill fremgang','Reset progress','학습 기록 초기화'],
  resetConfirm:['Slette all fremgang i denne nettleseren? Dette kan ikke angres.','Delete all progress in this browser? This cannot be undone.','이 브라우저의 학습 기록을 모두 삭제할까요? 복구할 수 없습니다.'],
  local:['Fremgangen lagres i denne nettleseren.','Progress is saved in this browser.','학습 기록은 이 브라우저에 저장됩니다.'],
  storageError:['Nettleseren tillater ikke lagring. Fremgangen beholdes bare mens siden er åpen.','Browser storage is unavailable. Progress will only last while this page is open.','저장소를 사용할 수 없습니다. 페이지를 닫으면 학습 기록이 사라집니다.'],
  close:['Lukk','Close','닫기'], noResults:['Ingen tegn funnet','No characters found','검색 결과가 없습니다'],
  letterName:['Bokstavnavn','Letter name','글자 이름'], components:['Deler','Components','구성'], roman:['Romanisering','Romanization','로마자'],
  home:['Tilbake til oppsett','Back to setup','설정으로 돌아가기'], complete:['mestret','mastered','완료'],
  source:['Uttale og romanisering','Pronunciation & romanization','발음과 로마자'],
} satisfies Record<string, [string,string,string]>;
export type CopyKey = keyof typeof copy;
export const translate = (lang: Language, key: CopyKey) => copy[key][lang==='nb'?0:lang==='en'?1:2];
