export type Language = 'nb' | 'en' | 'ko';
const copy = {
  subtitle:['Lær det koreanske alfabetet','Learn the Korean alphabet','한글을 배워 보세요'],
  quiz:['Quiz','Quiz','퀴즈'], exam:['Eksamen','Exam','시험'], cards:['Flashcards','Flashcards','학습 카드'],
  overview:['Lær og utforsk','Learn & explore','배우고 탐색하기'], stats:['Din fremgang','Your progress','나의 학습 기록'],
  language:['Språk','Language','언어'], sound:['Lyd på','Sound on','소리 켜짐'], mute:['Lyd av','Sound off','소리 꺼짐'],
  practice:['LITT HVER DAG','A LITTLE EVERY DAY','매일 조금씩'], title:['Bli kjent med 한글','Get to know 한글','한글과 친해지기'],
  intro:['Velg tegnene du vil øve på. Ta det i ditt eget tempo.','Choose what to practise. Go at your own pace.','연습할 글자를 선택하고 자신의 속도로 공부하세요.'],
  groups:['Hva vil du øve på?','What would you like to practise?','무엇을 연습할까요?'],
  consonants:['Grunnkonsonanter','Basic consonants','기본 자음'], vowels:['Grunnvokaler','Basic vowels','기본 모음'],
  tense:['Doble konsonanter','Tense consonants','쌍자음'], extra:['Flere vokaler','More vowels','추가 모음'],
  syllables:['Stavelser','Syllables','음절'], finals:['Stavelser med 받침','Syllables with batchim','받침이 있는 음절'],
  all:['Alle','All','전체'], basic:['Grunntegn','Basics','기본 글자'], clear:['Tøm','Clear','해제'],
  chosen:['valgte tegn','selected characters','선택한 글자'], mode:['Hvordan vil du svare?','How will you answer?','어떻게 답할까요?'],
  typing:['Skriv svaret','Type the answer','직접 입력'], choice:['Flervalg','Multiple choice','객관식'],
  direction:['Spørsmålsretning','Question direction','문제 방향'], read:['Hangeul → latinske bokstaver','Hangeul → romanization','한글 → 로마자'],
  write:['Latinske bokstaver → hangeul','Romanization → Hangeul','로마자 → 한글'],
  count:['Antall spørsmål','Number of questions','문제 수'], start:['Start quiz','Start quiz','퀴즈 시작'],
  tipTitle:['Én bokstav. Mange muligheter.','One letter. Many possibilities.','하나의 글자, 다양한 가능성.'],
  tip:['Hangeul bygger stavelser av bokstaver. ㄱ + ㅏ blir 가. Legg til ㄴ, og du får 간.','Hangeul combines letters into syllable blocks. ㄱ + ㅏ makes 가. Add ㄴ to make 간.','한글은 자음과 모음을 모아 음절을 만듭니다. ㄱ + ㅏ는 가, 받침 ㄴ을 더하면 간이 됩니다.'],
  tryBuilder:['Prøv stavelsesbyggeren','Try the syllable builder','음절 만들기'], listen:['Hør uttalen','Hear pronunciation','발음 듣기'],
  audioMissing:['Ingen koreansk stemme tilgjengelig i denne nettleseren. Prøv en nettleser med koreansk talesyntese.','No Korean voice is available in this browser. Try a browser with Korean speech support.','이 브라우저에서 한국어 음성을 사용할 수 없습니다. 한국어 음성을 지원하는 브라우저를 사용해 주세요.'],
  audioSample:['Eksempeluttale','Example pronunciation','발음 예시'],
  answer:['Ditt svar','Your answer','정답 입력'], check:['Sjekk svaret','Check answer','정답 확인'], next:['Neste','Next','다음'],
  previous:['Forrige','Previous','이전'], cancel:['Avslutt økten','End session','학습 종료'], cancelConfirm:['Avslutte økten? Besvarte spørsmål blir lagret.','End this session? Answered questions will be saved.','학습을 종료할까요? 답한 문제는 저장됩니다.'],
  correct:['Riktig!','Correct!','정답!'], wrong:['Ikke helt.','Not quite.','다시 확인해 보세요.'], solution:['Riktig svar','Correct answer','정답'],
  timeout:['Tiden er ute','Time is up','시간 초과'], question:['Spørsmål','Question','문제'], score:['Riktige','Correct','정답 수'],
  romanPrompt:['Skriv med latinske bokstaver','Type the romanization','로마자를 입력하세요'], glyphPrompt:['Skriv hangeul-tegnet','Type the Hangeul character','한글을 입력하세요'],
  koreanKeyboard:['Bruk det koreanske tastaturet på telefonen eller PC-en.','Use the Korean keyboard on your phone or computer.','휴대폰이나 컴퓨터의 한국어 키보드를 사용하세요.'],
  results:['Godt jobbet. Fortsett litt til?','Nice work. Keep going?','수고했어요. 조금 더 연습할까요?'],
  retry:['Øv på feilene','Practise mistakes','틀린 문제 연습'], again:['Ta en ny quiz','Start another quiz','새 퀴즈 시작'],
  finished:['Økten er ferdig','Session complete','학습 완료'], accuracy:['Nøyaktighet','Accuracy','정확도'],
  examTitle:['Den store hangeul-testen','The Hangeul challenge','한글 실력 시험'],
  examIntro:['Alle tegn i valgt pensum, én gang hver. Skriv svaret på fem sekunder. Ett feil svar eller tidsavbrudd avslutter eksamen.','Every character in your chosen syllabus, once each. Type the answer within five seconds. One mistake or timeout ends the exam.','선택한 범위의 모든 글자가 한 번씩 나옵니다. 5초 안에 답하세요. 오답이나 시간 초과 시 시험이 종료됩니다.'],
  locked:['Eksamen åpner snart','The exam opens soon','시험이 곧 열립니다'],
  unlockDate:['Mandag 12. oktober 2026 · kl. 08:00 norsk tid','Monday 12 October 2026 · 08:00 Norway time','2026년 10월 12일 월요일 · 노르웨이 시간 08:00 (한국 시간 15:00)'],
  days:['dager','days','일'], hours:['timer','hours','시간'], minutes:['minutter','minutes','분'], seconds:['sekunder','seconds','초'],
  syllabus:['Velg pensum','Choose a syllabus','시험 범위 선택'], letters:['Alle 40 bokstaver','All 40 letters','전체 40개 글자'],
  full:['Bokstaver og stavelser','Letters & syllables','글자와 음절'], examStart:['Start eksamen','Start exam','시험 시작'],
  examRule:['100 % riktig · 5 sekunder per tegn · ingen hint','100% correct · 5 seconds per character · no hints','정확도 100% · 글자당 5초 · 힌트 없음'],
  passed:['Eksamen bestått!','Exam passed!','시험 합격!'], failed:['Øv litt til og prøv igjen','Practise a little more and try again','조금 더 연습하고 다시 도전하세요'],
  attempted:['Besvart','Answered','답한 문제'],
  cardTitle:['Ett tegn om gangen','One character at a time','한 글자씩 차근차근'],
  cardIntro:['Tenk på svaret før du snur kortet.','Think of the answer before flipping the card.','카드를 뒤집기 전에 정답을 생각해 보세요.'],
  filter:['Tegngruppe','Character group','글자 종류'], shuffle:['Stokk kort','Shuffle cards','카드 섞기'],
  flip:['Trykk for å snu · mellomrom','Tap to flip · space','눌러서 뒤집기 · 스페이스'],
  needsPractice:['Må øves på','Needs practice','복습 필요'], mastered:['Mestret','Mastered','학습 완료'],
  reviewOnly:['Kun tegn som må øves på','Only characters needing practice','복습할 글자만'],
  emptyReview:['Ingen tegn å repetere her ennå. Velg en annen gruppe eller slå av filteret.','No characters to review here yet. Choose another group or turn off the filter.','복습할 글자가 없습니다. 다른 종류를 선택하거나 필터를 해제하세요.'],
  search:['Søk etter tegn eller romanisering','Search characters or romanization','글자 또는 로마자 검색'],
  referenceTitle:['Se mønsteret. Bygg en stavelse.','Find the pattern. Build a syllable.','규칙을 배우고 음절을 만들어 보세요.'],
  referenceIntro:['Klikk på et tegn for å se navn og høre et uttaleeksempel.','Select a character to see its name and hear a pronunciation example.','글자를 선택하면 이름과 발음 예시를 확인할 수 있습니다.'],
  builder:['Stavelsesbygger','Syllable builder','음절 만들기'], onset:['Startkonsonant','Initial consonant','초성'],
  medial:['Vokal','Vowel','중성'], final:['Sluttkonsonant','Final consonant','종성'], none:['Ingen','None','없음'],
  syllableNote:['Romaniseringen gjelder en enkelt stavelse. Uttalen kan endres når stavelser settes sammen til ord.','Romanization is for an isolated syllable. Pronunciation can change when syllables form words.','로마자는 단독 음절을 기준으로 합니다. 단어에서는 발음이 달라질 수 있습니다.'],
  consonantNote:['ㄱ, ㄷ og ㅂ har ulike lyder etter plassering. ㄹ kan være r eller l. ㅇ er stum først i en stavelse og ng til slutt.','ㄱ, ㄷ and ㅂ change sound with position. ㄹ can be r or l. ㅇ is silent initially and ng in final position.','ㄱ, ㄷ, ㅂ은 위치에 따라 소리가 달라집니다. ㄹ은 r 또는 l로 적습니다. ㅇ은 초성에서 소리가 없고 종성에서 ng로 적습니다.'],
  vowelNote:['eo og eu er én vokallyd hver. De uttales ikke som to separate bokstaver. ㅐ og ㅔ høres ofte like ut i moderne koreansk.','eo and eu each represent one vowel, not two separate sounds. ㅐ and ㅔ often sound alike in modern Korean.','eo와 eu는 각각 하나의 모음 소리입니다. 현대 한국어에서는 ㅐ와 ㅔ가 비슷하게 들리는 경우가 많습니다.'],
  extraNote:['Denne gruppen samler 11 vokalbokstaver utover de 10 grunnvokalene. Ikke alle er fonetisk diftonger.','This group contains 11 vowel letters beyond the 10 basic vowel letters. They are not all phonetic diphthongs.','이 그룹은 기본 모음 10개 외의 모음 11개입니다. 음성학적으로 모두 이중 모음인 것은 아닙니다.'],
  finalNote:['받침 er konsonanten nederst i stavelsen. I slutten av en isolert stavelse reduseres sluttlydene til k, n, t, l, m, p eller ng.','Batchim is the consonant at the bottom of a syllable. At the end of an isolated syllable, final sounds reduce to k, n, t, l, m, p or ng.','받침은 음절 아래에 놓입니다. 단독 음절의 끝소리는 ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅇ 중 하나로 발음됩니다.'],
  statsTitle:['Små økter. Synlig fremgang.','Small sessions. Real progress.','조금씩 연습하고 실력을 키우세요.'],
  statsIntro:['Tre riktige svar på rad gir mestring. Feil svar sender tegnet tilbake til øving.','Three correct answers in a row mark a character as mastered. A mistake sends it back to practice.','같은 글자를 세 번 연속 맞히면 학습 완료로 표시됩니다. 틀리면 다시 복습 목록으로 돌아갑니다.'],
  answered:['Besvarte spørsmål','Questions answered','답한 문제 수'], best:['Beste serie','Best streak','최고 연속 정답'],
  mastery:['Mestrede bokstaver','Letters mastered','학습 완료 글자'], hard:['Her kan du bli bedre','Worth another look','다시 연습할 글자'],
  noStats:['Ingen svar ennå. Ta en quiz, så finner vi ut hva du bør øve på.','No answers yet. Take a quiz to find out what to practise.','아직 기록이 없습니다. 퀴즈로 연습할 글자를 찾아보세요.'],
  noMistakes:['Ingen feil registrert. Fortsett å øve!','No mistakes recorded. Keep practising!','틀린 문제가 없습니다. 계속 연습해 보세요!'],
  reset:['Nullstill fremgang','Reset progress','학습 기록 초기화'],
  resetConfirm:['Slette all fremgang i denne nettleseren? Dette kan ikke angres.','Delete all progress in this browser? This cannot be undone.','이 브라우저의 학습 기록을 모두 삭제할까요? 복구할 수 없습니다.'],
  local:['Fremgangen lagres i denne nettleseren.','Progress is saved in this browser.','학습 기록은 이 브라우저에 저장됩니다.'],
  storageError:['Nettleseren tillater ikke lagring. Fremgangen beholdes bare mens siden er åpen.','Browser storage is unavailable. Progress will only last while this page is open.','저장소를 사용할 수 없습니다. 페이지를 닫으면 학습 기록이 사라집니다.'],
  close:['Lukk','Close','닫기'], noResults:['Ingen tegn funnet','No characters found','검색 결과가 없습니다'],
  name:['Bokstavnavn / deler','Letter name / components','글자 이름 / 구성'], roman:['Romanisering','Romanization','로마자'],
  home:['Tilbake til oppsett','Back to setup','설정으로 돌아가기'], complete:['mestret','mastered','완료'],
  source:['Uttale og romanisering','Pronunciation & romanization','발음과 로마자'],
} satisfies Record<string, [string,string,string]>;
export type CopyKey = keyof typeof copy;
export const translate = (lang: Language, key: CopyKey) => copy[key][lang==='nb'?0:lang==='en'?1:2];
